logLevel: info
wsEndpoint: "wss://kusama-rpc.polkadot.io/"
retryPolicy: 
  delayMillis: 10000
  maxAttempts: 5
claimsCheckOnly:
- alias: validator-000
  validatorAddress: "<validator-000-stash-address>"
- alias: validator-001
  validatorAddress: "<validator-001-stash-address>"  
